-- ============================================================
-- Migración IoTGaraje — vehículos, dimensiones de garaje y aprobación
-- Ejecutar UNA sola vez en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- ------------------------------------------------------------
-- 1) GARAJES: dimensiones físicas + estado de aprobación
-- ------------------------------------------------------------
alter table garajes add column if not exists ancho            numeric;      -- metros
alter table garajes add column if not exists largo            numeric;      -- metros (profundidad)
alter table garajes add column if not exists metros_cuadrados numeric;      -- área
alter table garajes add column if not exists descripcion      text;
alter table garajes add column if not exists estado           text not null default 'aprobado';
--   estado: 'pendiente' | 'aprobado' | 'rechazado'
--   Los garajes que ya existían quedan 'aprobado' para no romper nada.

-- ------------------------------------------------------------
-- 2) VEHÍCULOS del cliente (datos completos + aprobación)
-- ------------------------------------------------------------
create table if not exists vehiculos (
  id             bigint generated by default as identity primary key,
  usuario_id     bigint not null references usuarios(id) on delete cascade,
  placa          text not null,
  chasis         text not null,
  tipo           text not null,                 -- 'auto' | 'camioneta' | 'camion'
  factor_espacio integer not null default 1,    -- auto=1, camioneta=2, camion=3
  marca          text,
  modelo         text,
  color          text,
  foto_url       text,
  estado         text not null default 'pendiente', -- 'pendiente'|'aprobado'|'rechazado'
  created_at     timestamptz not null default now()
);

create index if not exists vehiculos_usuario_idx on vehiculos (usuario_id);

alter table vehiculos enable row level security;
drop policy if exists "vehiculos_select" on vehiculos;
create policy "vehiculos_select" on vehiculos for select using (true);
drop policy if exists "vehiculos_insert" on vehiculos;
create policy "vehiculos_insert" on vehiculos for insert with check (true);
drop policy if exists "vehiculos_update" on vehiculos;
create policy "vehiculos_update" on vehiculos for update using (true);
drop policy if exists "vehiculos_delete" on vehiculos;
create policy "vehiculos_delete" on vehiculos for delete using (true);

-- ------------------------------------------------------------
-- 3) RESERVAS: vehículo asociado + flujo de aprobación del dueño
-- ------------------------------------------------------------
alter table reservas add column if not exists vehiculo_id bigint references vehiculos(id) on delete set null;
--   estado de reserva ahora puede ser:
--   'pendiente'  → esperando que el dueño acepte
--   'activa'     → aceptada / vigente
--   'cancelada'  → cancelada por el cliente
--   'rechazada'  → rechazada por el dueño
