-- ============================================================
-- Migración IoTGaraje — reservas con horario + calificaciones
-- Ejecutar UNA sola vez en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) Reservas con fecha y hora de inicio/fin.
--    Las reservas viejas (sin horario) siguen funcionando: el backend
--    las trata como "activas ahora" hasta que se cancelen.
alter table reservas add column if not exists inicio timestamptz;
alter table reservas add column if not exists fin    timestamptz;

-- 2) Tabla de calificaciones: un usuario puede calificar cada garaje
--    una sola vez (si vuelve a calificar, se actualiza su nota).
create table if not exists calificaciones (
  id         bigint generated by default as identity primary key,
  garaje_id  bigint not null references garajes(id) on delete cascade,
  usuario_id bigint not null references usuarios(id) on delete cascade,
  estrellas  integer not null check (estrellas between 1 and 5),
  comentario text,
  created_at timestamptz not null default now(),
  unique (garaje_id, usuario_id)
);

-- 3) Permitir que el backend (rol anon) lea y escriba calificaciones.
--    La validación de identidad la hace el backend con JWT.
alter table calificaciones enable row level security;

drop policy if exists "calificaciones_select" on calificaciones;
create policy "calificaciones_select" on calificaciones
  for select using (true);

drop policy if exists "calificaciones_insert" on calificaciones;
create policy "calificaciones_insert" on calificaciones
  for insert with check (true);

drop policy if exists "calificaciones_update" on calificaciones;
create policy "calificaciones_update" on calificaciones
  for update using (true);
