-- ============================================================
-- Migración IoTGaraje — chat propietario ↔ cliente
-- Ejecutar UNA sola vez en: Supabase → SQL Editor → New query → Run
-- ============================================================

-- Cada conversación se identifica por (garaje_id, cliente_id).
-- El propietario es el dueño del garaje; el emisor de cada mensaje
-- puede ser el cliente o el propietario.
create table if not exists mensajes (
  id         bigint generated by default as identity primary key,
  garaje_id  bigint not null references garajes(id) on delete cascade,
  cliente_id bigint not null references usuarios(id) on delete cascade,
  emisor_id  bigint not null references usuarios(id) on delete cascade,
  texto      text not null check (length(texto) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists mensajes_conversacion_idx
  on mensajes (garaje_id, cliente_id, created_at);

-- El backend valida la identidad con JWT; permitimos acceso vía anon key.
alter table mensajes enable row level security;

drop policy if exists "mensajes_select" on mensajes;
create policy "mensajes_select" on mensajes for select using (true);

drop policy if exists "mensajes_insert" on mensajes;
create policy "mensajes_insert" on mensajes for insert with check (true);
